server:
  port: 8888

spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
      id:
        new_generator_mappings: false
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: app-hikari-pool
      register-mbeans: false
      connection-test-query: SELECT 1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.querydsl.sql: DEBUG
