server:
  port: 8888
  error:
    include-stacktrace: always

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: app-hikari-pool
      register-mbeans: false
      connection-test-query: SELECT 1
graphiql:
  props:
    variables:
      editorTheme: "solarized dart"


logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.querydsl.sql: DEBUG
